name: Insert into a demo deta db

on:
  workflow_dispatch:

jobs:
  build-db:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: pip
    - name: Install python dependencies
      run: |-
        pip install -r requirements.txt
    - run: python3 db-insert.py
      env:
        PROJECT_KEY: ${{ secrets.PROJECT_KEY }}
